/* sw.js — 萤火归途 offline service worker, generated by tools/remake/build.js. build 635861f */
'use strict';
const BUILD = '635861f', CACHE = 'firefly-' + BUILD, PAGE = 'index.html';
const PRECACHE = [PAGE, 'manifest.json', 'icons/icon-192.png', 'icons/icon-512.png', 'icons/maskable-192.png', 'icons/maskable-512.png'];
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE.map((u) => new Request(u, { cache: 'reload' })))).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k.startsWith('firefly-') && k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
// the page: CACHE FIRST from this build's own cache (the single-file page is ~2.6 MB gzipped — fetching it on every
// launch left a slow / flaky connection on a blank screen for 30 s+, 2026-10-05 Fold7 report). A redeploy is picked up
// by the browser's sw.js update check: the new SW precaches its page in the background, takes over, the game shows
// 「新版本已就绪 · 下次启动生效」 and the next launch runs it. Network only when this cache has no page.
function page(req) {
  return caches.open(CACHE).then((c) => c.match(PAGE).then((hit) => hit || fetch(req.url.split('#')[0], { cache: 'no-store' }).then((r) => {
    if (r.ok && r.type === 'basic') c.put(PAGE, r.clone());
    return r;
  }).catch(() => caches.match(PAGE, { ignoreSearch: true }).then((h) => h || Response.error()))));
}
self.addEventListener('fetch', (e) => {
  const req = e.request; if (req.method !== 'GET') return;
  const url = new URL(req.url); if (url.origin !== location.origin) return;
  const scope = new URL(self.registration.scope);
  if (req.mode === 'navigate' || url.pathname === scope.pathname || url.pathname === scope.pathname + PAGE) { e.respondWith(page(req)); return; }
  e.respondWith(caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).then((r) => {
    if (r.ok && r.type === 'basic' && url.pathname.startsWith(scope.pathname) && !url.pathname.endsWith('/sw.js')) { const cp = r.clone(); caches.open(CACHE).then((c) => c.put(req, cp)); }
    return r;
  })));
});
self.addEventListener('message', (e) => { if (e.data === 'build') e.source && e.source.postMessage({ build: BUILD }); });
