/* sw.js — 萤火归途 offline service worker, generated by tools/remake/build.js. build 65a6121 */
'use strict';
const BUILD = '65a6121', CACHE = 'firefly-' + BUILD, PAGE = 'index.html';
const PRECACHE = [PAGE, 'manifest.json', 'icons/icon-192.png', 'icons/icon-512.png', 'icons/maskable-192.png', 'icons/maskable-512.png'];
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE.map((u) => new Request(u, { cache: 'reload' })))).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k.startsWith('firefly-') && k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
// the page: network first (a redeploy shows up on the next launch while online), cached copy when offline or slow
function page(req) {
  return caches.open(CACHE).then((c) => c.match(PAGE).then((hit) => {
    const net = fetch(req.url.split('#')[0], { cache: 'no-store' }).then((r) => { if (r.ok && r.type === 'basic') { c.put(PAGE, r.clone()); return r; } return hit || r; });
    if (!hit) return net;
    const slow = new Promise((ok) => setTimeout(() => ok(hit), 3500));
    return Promise.race([net.catch(() => hit), slow]);
  }));
}
self.addEventListener('fetch', (e) => {
  const req = e.request; if (req.method !== 'GET') return;
  const url = new URL(req.url); if (url.origin !== location.origin) return;
  const scope = new URL(self.registration.scope);
  if (req.mode === 'navigate' || url.pathname === scope.pathname || url.pathname === scope.pathname + PAGE) { e.respondWith(page(req)); return; }
  e.respondWith(caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).then((r) => {
    if (r.ok && r.type === 'basic' && url.pathname.startsWith(scope.pathname) && !url.pathname.endsWith('/sw.js')) { const cp = r.clone(); caches.open(CACHE).then((c) => c.put(req, cp)); }
    return r;
  })));
});
self.addEventListener('message', (e) => { if (e.data === 'build') e.source && e.source.postMessage({ build: BUILD }); });
